config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  namespace :manage do
    resources :users
  end

  resources :roles

  get 'histories', to: 'histories#index'
  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return can :manage, :all if user.is_root?
    return unless user.role

    user.role.permissions.each do |subject, actions|
      can actions.map(&:to_sym),
          (klass = subject.classify.safe_constantize) ? klass : subject.to_sym
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  store_accessor :permissions

  has_many :users, dependent: :nullify

  validates :name, presence: true, uniqueness: true

  has_paper_trail only: [:name, :permissions]
end

app/models/user.rb
class User < ApplicationRecord
  include StateEnum

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role, required: false

  has_attached_file :avatar,
    styles: { thumb: ['300x300#', :jpg] },
    convert_options: { thumb: '-quality 80 -strip' },
    path: ':rails_env/user/:attachment/:id_:created_timestamp_:style.:extension',
    url: ':rails_env/user/:attachment/:id_:created_timestamp_:style.:extension'

  validates_attachment :avatar,
    content_type: {
      content_type: %r{^image/(jpg|jpeg|pjpeg|png|x-png|gif)$}
    },
    size: { less_than: 4.megabyte }

  validates :full_name, presence: true

  has_paper_trail on: [:update, :create], only: [:full_name, :email, :is_root]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_breadcrumb I18n.t('breadcrumb.home'), :root_path
  before_action :authenticate_user!
  before_action :set_paper_trail_whodunnit

  rescue_from CanCan::AccessDenied do
    if current_user.nil?
      session[:next] = request.fullpath
      redirect_to login_url, alert: I18n.t('helpers.required_login')
    else
      render file: Rails.root.join('public', '403.html'), status: 403, layout: false
    end
  end

  load_and_authorize_resource except: [:index], unless: :devise_controller?
  authorize_resource only: [:index]

  private

  def user_for_paper_trail
    user_signed_in? ? current_user.id : 'Guest'
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  skip_authorize_resource

  def index
    add_breadcrumb I18n.t('breadcrumb.histories'), histories_path

    @versions = PaperTrail::Version.order('created_at DESC')
                                   .page(params[:page])
                                   .per(params[:per])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorize_resource

  def index; end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:full_name, :email, :avatar,
                                 :password, :password_confirmation, :current_password)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :add_default_breadcrumb
  before_action :find_resource, only: %w(show edit update destroy)

  def index
    @roles ||= Role.page(params[:page]).per(params[:per])
  end

  def show
    add_breadcrumb @role.name, role_path(@role)
    @users ||= @role.users.page(params[:page]).per(params[:per])
  end

  def new
    add_breadcrumb I18n.t('helpers.new'), new_role_path
    @role = Role.new(permissions: {})
  end

  def create
    @role = Role.new(role_params)
    @role.permissions = permission_to_hash(params[:role][:permissions])

    if @role.save
      redirect_to roles_path, notice: I18n.t('helpers.create.successfully')
    else
      render :new
    end
  end

  def edit
    add_breadcrumb @role.name, edit_role_path(@role)
  end

  def update
    @role.name = params[:role][:name]
    @role.permissions = permission_to_hash(params[:role][:permissions])

    if @role.save
      redirect_to roles_path, notice: I18n.t('helpers.update.successfully')
    else
      render :edit
    end
  end

  def destroy
    @role.destroy

    redirect_to roles_url, notice: I18n.t('helpers.destroy.successfully')
  end

  private

  def add_default_breadcrumb
    add_breadcrumb I18n.t('breadcrumb.roles'), roles_path
  end

  def find_resource
    @role ||= Role.find(params[:id])
  end

  def role_params
    params.require(:role).permit(:id, :name)
  end

  def permission_to_hash(permissions)
    options = {}
    permissions.each do |key, value|
      options[key] = value.keys
    end
    options
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/button_helper.rb
module ButtonHelper
  def fontawesome(name)
    "<i class=\"fa fa-#{name}\"></i>".html_safe
  end

  def display_tooltip(title, position = 'top')
    {
      'data-placement' => position,
      'data-toggle' => 'tooltip',
      'data-original-title' => title
    }
  end

  def new_resource_btn(model, path, title = nil)
    title ||= I18n.t('helpers.add_new_resource', model_name: model.model_name.human)

    link_to title, path, display_tooltip(title).merge(class: 'btn btn-warning')
  end

  def view_resource_btn(path)
    link_to fontawesome('search'), path, display_tooltip(t('helpers.view'))
  end

  def edit_resource_btn(path)
    link_to fontawesome('edit'), path, display_tooltip(t('helpers.edit'))
  end

  def destroy_resource_btn(path)
    link_to fontawesome('trash'), path,
            display_tooltip(t('helpers.delete')).merge(method: :delete,
                                                       data: { confirm: t('helpers.are_you_sure') })
  end
end

app/helpers/datetime_helper.rb
#
# /app/helpers/datetime_helper.rb
#
module DatetimeHelper
  #
  # Format date, datetime into date format.
  #
  # @param [Date] object Object must be a Date, DateTime or Time object.
  # @param [Hash] options
  #   format: I18n format
  #
  # @return [String] date in human format.
  #
  # @example
  #   format_date(Time.now)  # => "31/05/2017"
  #   format_dat(Date.today) # => "31/05/2017"
  #
  def format_date(object, options = {})
    return I18n.l(object, format: options[:format]) if object.is_a?(Date)

    I18n.l(object, format: :date_only)
  rescue I18n::ArgumentError
    ''
  end

  #
  # Format datetime.
  #
  # @param [Date] object Object must be a Date, DateTime or Time object.
  # @param [Hash] options
  #   format: I18n format
  #
  # @return [String] date in human format.
  #
  # @example
  #   format_datetime(Time.now)   # => "23:02:02 31/05/2017"
  #   format_datetime(Date.today) # => "31/05/2017"
  #
  def format_datetime(object, options = {})
    I18n.l(object, format: options[:format])
  rescue I18n::ArgumentError
    ''
  end
end

app/helpers/history_helper.rb
module HistoryHelper
  def track_change(version)
    return unless version.event == 'update'
    html = "<ul>"
    version.changeset.each do |atrib, value|
      html += "<li><strong>#{atrib}</strong>: "
      html += value[0].blank? ? "empty -> " : "\"#{value[0]}\" -> "
      html += "\"#{value[1]}\""
    end
    html += "</li></ul>"
    html.html_safe
  end

  def history_event(version)
    color = case version.event
            when 'create'
              'muted'
            when 'update'
              'primary'
            when 'destroy'
              'danger'
            end
    "<span class=\"text-#{color}\">#{version.event}</span>".html_safe
  end
end

app/helpers/roles_helper.rb
module RolesHelper
  def resource_class
    %w(user)
  end
end

app/helpers/user_helper.rb
module UserHelper
  def user_avatar(user)
    avatar_url = user.avatar.file? ? user.avatar.url(:thumb) : 'avatar-1.jpg'

    image_tag avatar_url, alt: 'Avatar', class: 'img-fluid rounded-circle'
  end
end

app/views/histories/index.html.slim
section.charts
  .container-fluid
    header
      h1.h3.display &nbsp;
    .row
      .col-md-12
        .card
          .card-header.d-flex.align-items-center
            h2.h5.display Histories
          .card-body
            table.table.table-striped.table-hover
              thead
                td #
                td= t('.actor')
                td= t('.action')
                td= t('.object_type')
                td= t('.object_id')
                td= t('.timestamp')
                td= t('.changeset')
              tbody
                - @versions.each do |version|
                  tr
                    td= version.id
                    td= version.whodunnit ? link_to(version.whodunnit, manage_user_path(version.whodunnit)) : version.whodunnit
                    td= history_event(version)
                    td= version.item_type
                    td= version.item_id
                    td= format_datetime(version.created_at)
                    td= track_change(version)

app/views/home/index.html.slim
section.dashboard-counts.section-padding
  .container-fluid
    .row
      .col-xl-2.col-md-4.col-6
        .wrapper.count-title.d-flex
          .icon
            i.icon-user
          .name
            strong.text-uppercase New Clients
            span Last 7 days
            .count-number 25
      .col-xl-2.col-md-4.col-6
        .wrapper.count-title.d-flex
          .icon
            i.icon-padnote
          .name
            strong.text-uppercase Work Orders
            span Last 5 days
            .count-number 400
      .col-xl-2.col-md-4.col-6
        .wrapper.count-title.d-flex
          .icon
            i.icon-check
          .name
            strong.text-uppercase New Quotes
            span Last 2 months
            .count-number 342
      .col-xl-2.col-md-4.col-6
        .wrapper.count-title.d-flex
          .icon
            i.icon-bill
          .name
            strong.text-uppercase New Invoices
            span Last 2 days
            .count-number 123
      .col-xl-2.col-md-4.col-6
        .wrapper.count-title.d-flex
          .icon
            i.icon-list
          .name
            strong.text-uppercase Open Cases
            span Last 3 months
            .count-number 92
      .col-xl-2.col-md-4.col-6
        .wrapper.count-title.d-flex
          .icon
            i.icon-list-1
          .name
            strong.text-uppercase New Cases
            span Last 7 days
            .count-number 70

section.statistics.section-padding.section-no-padding-bottom
  .container-fluid
    .row.d-flex.align-items-stretch
      .col-lg-4
        /! Income
        .wrapper.income.text-center
          .icon
            i.icon-line-chart
          .number 126,418
          strong.text-primary All Income
          p Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do.
      .col-lg-4
        /! Monthly Usage
        .wrapper.data-usage
          h2.display.h4 Monthly Usage
          .row.d-flex.align-items-center
            .col-sm-6
              #progress-circle.d-flex.align-items-center.justify-content-center
            .col-sm-6
              strong.text-primary 80.56 Gb
              small Current Plan
              span 100 Gb Monthly
          p Lorem ipsum dolor sit amet, consectetur adipisicing.
      .col-lg-4
        /! User Actibity
        .wrapper.user-activity
          h2.display.h4 User Activity
          .number 210
          h3.h4.display Social Users
          .progress
            .progress-bar.progress-bar.bg-primary aria-valuemax="100" aria-valuemin="0" aria-valuenow="25" role="progressbar" style=("width: 25%")
          .page-statistics.d-flex.justify-content-between
            .page-visites
              span Pages Visites
              strong 230
            .new-visites
              span New Visites
              strong 73.4%

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="This is a skeleton for new Rails project" name="description" /
    meta content="Nobi Hoang, Hoang Hoa, rails" name="keywords"
    meta content="width=device-width, initial-scale=1" name="viewport" /
    meta content="all,follow" name="robots" /
    title Skeleton Rails

    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    link href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet" /
    link href="favicon.png" rel=("shortcut icon") /
    /! Tweaks for older IEs
    /![if lt IE 9]
      | <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script
      | <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script
  body
    = render partial: "shared/sidebar"

    .page.home-page
      = render partial: "shared/header"

      = render partial: "shared/breadcrumb"

      = yield

      = render partial: "shared/footer"
    = javascript_include_tag 'application'

app/views/layouts/blank.html.slim
doctype html
html
  head
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="This is a skeleton for new Rails project" name="description" /
    meta content="Nobi Hoang, Hoang Hoa, rails" name="keywords"
    meta content="width=device-width, initial-scale=1" name="viewport" /
    meta content="all,follow" name="robots" /
    title Skeleton Rails

    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    link href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet" /
    link href="favicon.ico" rel=("shortcut icon") /
    /! Tweaks for older IEs
    /![if lt IE 9]
      | <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script
      | <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script
  body
    .page.login-page
      = yield
      = render partial: "shared/footer"
    = javascript_include_tag 'application'

app/views/roles/_form.html.slim
section.forms
  .container-fluid
    header
      h1.h3.display &nbsp;
    .row
      .col-md-12.col-lg-12
        .card
          .card-header.d-flex.align-items-center
            h2.h5.display.display= t('.role')
          .card-body
            = simple_form_for(@role, html: { class: "form-horizontal" }, wrapper: :horizontal_form) do |f|
              fieldset
                = f.input :name, class: "form-control", autofocus: true
              fieldset
                table.table.table-striped.table-hover
                  thead
                    th Module
                    th Manage
                    th Read
                    th Create
                    th Update
                    th Destroy
                  tbody
                    - resource_class.each do |resource|
                      tr
                        td= resource.classify.safe_constantize.model_name.human
                        - %w( manage read create update destroy ).each do |per|
                          td= check_box_tag "role[permissions][#{resource}][#{per}]", true, @role.permissions[resource] && @role.permissions[resource].include?(per)

              .form-group.row
                .offset-sm-4.col-sm-8
                  .btn-toolbar
                    = f.submit t('helpers.submit'), class: "btn btn-primary"
                    = link_to t('helpers.cancel'), :back, class: "btn"

app/views/roles/_role.html.slim
tr
  td= link_to role.id, role_path(role)
  td= role.name
  td= role.users.count
  td
    - if can?(:read, role)
      = view_resource_btn role_path(role)
    - if can?(:update, role)
      = edit_resource_btn edit_role_path(role)
    - if can?(:destroy, role)
      = destroy_resource_btn role_path(role)

app/views/roles/edit.html.slim
= render 'form'

app/views/roles/index.html.slim
section.charts
  .container-fluid
    header
      - if can?(:create, Role)
        = new_resource_btn(Role, new_role_path)
    .row
      .col-md-12
        .card
          .card-header.d-flex.align-items-center
            h2.h5.display Roles
          .card-body
            table.table.table-striped.table-hover
              thead
                tr
                  td #
                  td= Role.human_attribute_name(:name)
                  td= Role.human_attribute_name(:total_users)
                  td
              tbody
                - @roles.each do |role|
                  = render partial: "/roles/role", locals: { role: role }
            .row
              .col-sm-3

              .col-sm-6.text-center
                = paginate @roles

app/views/roles/new.html.slim
= render 'form'

app/views/roles/show.html.slim
section.charts
  .container-fluid
    header
      h1.h3.display= "Role: #{@role.name}"
    .row
      .col-md-12
        .card
          .card-header.d-flex.align-items-center
              h2.h5.display Users
          .card-body
            table.table.table-striped.table-hover
              thead
                tr
                  td #
                  td= User.human_attribute_name(:full_name)
                  td
              tbody
                - @users.each do |user|
                  tr
                    td= link_to user.id, user_path(user)
                    td= link_to user.full_name, user_path(user)
            .row
              .col-sm-3

              .col-sm-6.text-center
                = paginate @users

app/views/shared/_breadcrumb.html.slim
.breadcrumb-holder
  .container-fluid
    ul.breadcrumb
      = render_breadcrumbs separator: ' / '

app/views/shared/_footer.html.slim
footer.main-footer
  .container-fluid
    .row
      .col-sm-6
        p
          = "Copy right "
          = link_to " Nobi Hoang", "mailto:nobi.hoa@gmail.com"
          |  &copy;
          = " #{Date.current.year}"
      .col-sm-6.text-right
        p
          | Design by
          a.external href="https://bootstrapious.com"  Bootstrapious

app/views/shared/_header.html.slim
header.header
  nav.navbar
    .container-fluid
      .navbar-holder.d-flex.align-items-center.justify-content-between
        .navbar-header
          a#toggle-btn.menu-btn href="#"
            i.icon-bars
          a.navbar-brand href="index.html"
          .brand-text.d-none.d-md-inline-block
            span Skeleton RAILS
            strong.text-primary &nbsp; Dashboard
        ul.nav-menu.list-unstyled.d-flex.flex-md-row.align-items-md-center
          li.nav-item
            = link_to destroy_user_session_path, method: :delete, class: "nav-link" do
              = t("helpers.logout")
              i.fa.fa-sign-out

app/views/shared/_sidebar.html.slim
nav.side-navbar
  .side-navbar-wrapper
    .sidenav-header.d-flex.align-items-center.justify-content-center
      .sidenav-header-inner.text-center
        = user_avatar(current_user)
        h2.h5.text-uppercase= current_user.full_name
        span.text-uppercase= current_user.role ? current_user.role.name : ''
      .sidenav-header-logo
        = link_to root_path, class: "brand-small text-center" do
          strong S
          strong.text-primary R
    .main-menu
      ul#side-main-menu.side-menu.list-unstyled
        li.active
          = link_to root_path do
            i.icon-home
            span= t('sidebar.home')
        li
          = link_to histories_path do
            i.fa.fa-gear
            span= t('sidebar.histories')
    .admin-menu
      ul#side-admin-menu.side-menu.list-unstyled
        li
          a aria-expanded="false" data-toggle="collapse" href="#pages-nav-list"
            i.fa.fa-users
            span= t('sidebar.users_and_roles')
          .arrow.pull-right
            i.fa.fa-angle-down
          ul#pages-nav-list.collapse.list-unstyled
            li= link_to t('sidebar.users'), manage_users_path
            li= link_to t('sidebar.roles'), roles_path